//cut windows in upper ring
//originally, I used a loop, but then the windows looked too 
//regular. So I wrote the output of a little program in a file
//and deleted part of the windows manually.

object {upper_ring
clipped_by{
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*  1 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*  4 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr> 
rotate y*  7 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 10 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 13 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 16 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 19 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 22 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 25 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 28 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 31 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 34 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 37 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 40 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 43 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 46 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 49 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 52 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 55 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 58 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 61 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 64 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 67 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 70 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 73 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 76 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 79 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 82 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 85 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 88 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 91 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 94 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y* 97 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*100 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*103 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*106 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*109 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*112 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*115 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*118 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*121 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*124 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*127 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*130 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*133 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*136 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*139 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*142 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*145 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*148 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*151 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*154 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*157 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*160 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*163 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*166 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*169 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*172 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*175 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*178 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*181 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*184 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*187 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*190 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*193 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*196 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*199 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*202 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*205 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*208 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*211 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*214 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*217 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*220 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*223 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*226 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*229 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*232 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*235 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*238 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*241 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*244 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*247 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*250 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*253 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*256 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*259 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*262 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*265 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*268 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*271 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*274 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*277 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*280 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*283 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*286 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*289 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*292 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*295 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*298 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*301 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*304 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*307 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*310 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*313 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*316 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*319 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*322 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*325 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*328 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*331 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*334 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*337 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*340 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*343 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*346 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*349 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*352 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*355 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.1*dr>,<.07*dr,hr,-or+.23*dr>
rotate y*358 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*  1 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*  4 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*  7 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 10 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 13 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 16 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 19 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 22 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 25 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 28 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 31 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 34 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 37 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 40 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 43 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 46 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 49 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 52 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 55 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 58 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 61 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 64 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 67 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 70 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 73 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 76 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 79 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 82 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 85 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 88 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 91 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 94 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y* 97 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*100 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*103 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*106 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*109 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*112 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*115 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*118 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*121 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*124 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*127 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*130 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*133 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*136 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*139 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*142 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*145 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*148 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*151 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*154 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*157 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*160 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*163 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*166 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*169 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*172 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*175 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*178 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*181 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*184 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*187 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*190 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*193 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*196 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*199 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*202 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*205 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*208 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*211 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*214 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*217 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*220 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*223 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*226 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*229 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*232 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*235 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*238 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*241 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*244 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*247 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*250 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*253 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*256 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*259 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*262 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*265 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*268 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*271 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*274 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*277 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*280 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*283 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*286 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*289 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*292 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*295 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*298 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*301 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*304 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*307 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*310 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*313 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*316 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*319 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*322 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*325 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*328 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*331 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*334 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*337 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*340 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*343 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*346 translate <0,ha-.8*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*349 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*352 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*355 translate <0,ha-.005*hr,0> inverse}
box{<-.07*dr,0,-or+.3*dr>,<.07*dr,hr,-or+.43*dr>
rotate y*358 translate <0,ha-.005*hr,0> inverse}
}}